# $ cloud-build-local . --config=cloudbuild.yaml --dryrun=false .
steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/eslint', '.']
images: ['gcr.io/$PROJECT_ID/eslint']
