# In this directory, run the following command to run this build
# cloud-build-local --config=cloudbuild.yaml --dryrun=false --substitutions BRANCH_NAME='example',_ACCOUNT='admin@flappy.org' .
# $ gcloud builds submit . --config=cloudbuild.yaml --substitutions BRANCH_NAME='example'
steps:
- name: 'gcr.io/${PROJECT_ID}/templater'
  env:
    - "TARGET_SERVICE_ACCOUNT=${_ACCOUNT}"
    - "TARGET_NAMESPACE=${BRANCH_NAME}"
  args: ['templates/*.yaml','generated']
- name: 'gcr.io/cloud-builders/kubectl'
  entrypoint: bash
  args:
  - '-c'
  - |
    cat <<EOF
      From here, we can use the generated files for the next steps, i.e. kubectl:
      $ kubectl apply -f generated
    EOF

substitutions:
    _ACCOUNT:




