apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${TARGET_SERVICE_ACCOUNT}
  namespace: "${TARGET_NAMESPACE}"
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: some-binding
  namespace: "${TARGET_NAMESPACE}"
subjects:
- kind: ServiceAccount
  name: ${TARGET_SERVICE_ACCOUNT}
  namespace: "${TARGET_NAMESPACE}"
roleRef:
  kind: Role
  name: some-role
  apiGroup: rbac.authorization.k8s.io