# In this directory, run the following command to build this builder.
# $ cloud-build-local --config=cloudbuild.yaml --dryrun=false .
# $ gcloud builds submit . --config=cloudbuild.yaml
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/${PROJECT_ID}/pytest', '.']
- name: 'gcr.io/${PROJECT_ID}/pytest'
  args: ['--version']
images: ['gcr.io/${PROJECT_ID}/pytest']